import { useEffect,useState } from 'react';
import { ChevronDown,ChevronUp,Plus,Save,Trash2,X } from 'lucide-react';
import { api } from '../../api';
import { Toggle } from './shared';

const LABELS={ executive_summary:'Executive summary',service_overview:'Service overview',ticket_summary:'Ticket summary',open_tickets:'Open tickets',period_tickets:'Period tickets',service_activities:'Service activities',tasks:'Tasks',projects:'Projects',maintenance_visits:'Maintenance Visits',recommendations:'Recommendations',risks:'Risks',upcoming_work:'Upcoming work',management_notes:'Management notes' };
const empty={ name:'',description:'',sections:Object.keys(LABELS),default_narratives:{},active:true,version:0 };
export function ManagedReportTemplatesTab() {
  const [rows,setRows]=useState([]),[form,setForm]=useState(empty),[selected,setSelected]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
  const load=async () => { const result=await api.managedReportTemplates();setRows(result.rows || []);return result.rows || []; };
  useEffect(() => { load().catch(failure => setError(failure.message)); },[]);
  const edit=row => { setSelected(row.id);setForm({ ...row,default_narratives:{ ...row.default_narratives } });setError('');setMessage(''); };
  const reset=() => { setSelected(null);setForm({ ...empty,sections:[...empty.sections],default_narratives:{} }); };
  const toggle=key => setForm(current => ({ ...current,sections:current.sections.includes(key)?current.sections.filter(value => value!==key):[...current.sections,key] }));
  const move=(index,direction) => setForm(current => { const sections=[...current.sections],target=index+direction;if (target<0 || target>=sections.length) return current;[sections[index],sections[target]]=[sections[target],sections[index]];return { ...current,sections }; });
  async function save() { setBusy(true);setError('');setMessage('');try { const saved=selected?await api.updateManagedReportTemplate(selected,form):await api.createManagedReportTemplate(form);await load();edit(saved);setMessage('Report template saved.'); } catch(failure) { setError(failure.message); } finally { setBusy(false); } }
  async function remove() { setBusy(true);setError('');try { await api.deleteManagedReportTemplate(selected);await load();reset();setMessage('Report template deleted.'); } catch(failure) { setError(failure.message); } finally { setBusy(false); } }
  return <div className="u-cf23e32"><aside className="card u-cc781ba"><button className="btn btn-primary btn-sm u-31b5119" onClick={reset}><Plus size={13} /> New template</button>{rows.map(row => <button key={row.id} className={`settings-nav-item${selected===row.id?' active':''}`} onClick={() => edit(row)}><span>{row.name}</span>{!row.active && <small>Inactive</small>}</button>)}</aside><section className="card">
    {error && <div className="error-msg" role="alert">{error}</div>}{message && <div className="alert alert-success">{message}</div>}
    <div className="form-group"><label>Template name</label><input maxLength={120} value={form.name} onChange={event => setForm(current => ({ ...current,name:event.target.value }))} /></div><div className="form-group"><label>Description</label><textarea rows={2} maxLength={1000} value={form.description} onChange={event => setForm(current => ({ ...current,description:event.target.value }))} /></div><Toggle checked={form.active} onChange={active => setForm(current => ({ ...current,active }))} label="Active template" />
    <h3 className="u-999b629">Sections and order</h3><div className="u-5646293">{form.sections.map((key,index) => <div key={key} className="u-a4f885d"><span className="u-7829123">{index+1}. {LABELS[key]}</span><button className="btn btn-ghost btn-sm" aria-label={`Move ${LABELS[key]} up`} disabled={!index} onClick={() => move(index,-1)}><ChevronUp size={13} /></button><button className="btn btn-ghost btn-sm" aria-label={`Move ${LABELS[key]} down`} disabled={index===form.sections.length-1} onClick={() => move(index,1)}><ChevronDown size={13} /></button><button className="btn btn-ghost btn-sm" aria-label={`Remove ${LABELS[key]}`} onClick={() => toggle(key)}><X size={13} /></button></div>)}</div><div className="flex gap-8 u-a8b6fba">{Object.entries(LABELS).filter(([key]) => !form.sections.includes(key)).map(([key,label]) => <button key={key} className="btn btn-ghost btn-sm" onClick={() => toggle(key)}><Plus size={12} /> {label}</button>)}</div>
    <h3 className="u-999b629">Default narrative</h3><textarea rows={5} maxLength={10000} value={form.default_narratives.executive_summary || ''} onChange={event => setForm(current => ({ ...current,default_narratives:{ ...current.default_narratives,executive_summary:event.target.value } }))} placeholder="Default executive summary text" />
    <div className="flex gap-8 u-1b0f499"><button className="btn btn-primary" disabled={busy || !form.name.trim() || !form.sections.length} onClick={save}><Save size={14} /> Save template</button>{selected && <button className="btn btn-danger" disabled={busy} onClick={remove}><Trash2 size={14} /> Delete</button>}</div>
  </section></div>;
}
